name: Test

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.11"
      - name: Run plugin tests
        run: sbt test
      - name: Run sample app tests
        run: cd http4s-app && sbt test
